#!/usr/bin/env bash

program_exists() { command -v "$1" >/dev/null 2>&1; }

if program_exists "xbps-install"; then
  alias xs="xbps-query -Rs"
  alias xl="xbps-query -R" # 'l' for libra :) iyky
  alias xu="sudo xbps-install -Su"
  alias xo="sudo xbps-remove -o"
  alias xd="sudo xbps-remove"
fi

if program_exists "flatpak"; then
  alias fpi="flatpak install"
  alias fpr="flatpak uninstall"
  alias fps="flatpak search"
  alias fpu="flatpak update"
fi

if program_exists "git"; then
  alias gnp="~/scripts/newproject"
  alias ggp="~/scripts/getproject"
  alias gub="~/scripts/updatebranch"
  alias gsp="~/scripts/securepush"
fi

if program_exists "nvim"; then
  alias session="~/scripts/session"
fi

if program_exists "lazygit"; then
  alias lg="lazygit"
fi

alias edir="~/scripts/editdir"

t() { touch "$@"; }
+x() { chmod +x "$@"; }
t+x() {
  touch "$@"
  chmod +x "$@"
}
t+xe() { #n(ew) scr(ipt)
  touch "$@"
  chmod +x "$@"
  e "$@"
}

r() { nohup "$@" >/dev/null 2>&1 & } #run

if program_exists "eza"; then
  alias ls="eza --icons auto"
fi

unset -f program_exists
