#!/usr/bin/env bash
projectname=""
username="sjwesq"

while getopts 'dhp:u:' OPTION; do
  case "$OPTION" in
    d)
      create_repo=false
      ;;
    p)
      projectname="$OPTARG"
      ;;
    u)
      username="$OPTARG"
      ;;
  esac
done

if [[ -z $projectname ]]; then
  printf "ERROR: Use '-p' flag to choose project name\n"
  exit 1
fi

git clone git@github.com:"$username"/"$projectname"
cd $projectname
git remote rm origin
git remote add origin git@github.com:"$username"/"$projectname"
git remote set-url --push --add origin git@github.com:"$username"/"$projectname"
git remote set-url --push --add origin git@gitlab.com:"$username"/"$projectname"
git push --set-upstream origin main --dry-run
