[window]
dimensions = { columns = 100, lines= 30 }
option_as_alt = "Both"

[font]
normal = { family = "Inconsolata Nerd Font", style = "Regular"}
size = 14.0

[colors]
[colors.primary]
foreground="#d3c6aa"
background="#2d353b"

[colors.normal]
black="#374247"
red="#e67e80"
green="#a7c080"
yellow="#dbbc7f"
blue="#7fbbb3"
magenta="#d699b6"
cyan="#83c092"
white="#859289"

[colors.bright]
black="#404c51"
red="#e67e80"
green="#a7c080"
yellow="#dbbc7f"
blue="#7fbbb3"
magenta="#d699b6"
cyan="#83c092"
white="#9da9a0"

[cursor]
style = { shape="Block", blinking="on" }
